services:
  app:
    image: duckautomata/live-transcript-server
    container_name: live_transcript_server
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro,z
      - ./tmp:/app/tmp:z
    restart: always

  # Prometheus Server
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "8090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  # Grafana Server
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
